"use client";

import { useState, useRef, useCallback, useEffect } from "react";

// ------------------------------------------------------------------ //
// Types
// ------------------------------------------------------------------ //

interface Party {
  name: string;
  role: string;
  aliases: string[];
  source_pages?: number[];
}

interface KeyFact {
  text: string;
  pages?: number[];
}

interface TimelineEvent {
  date: string;
  event: string;
  pages?: number[];
}

interface SummaryMetadata {
  model: string;
  chunks_processed: number;
  filename: string;
}

interface CaseSummary {
  parties: Party[];
  key_facts: (string | KeyFact)[];
  timeline: TimelineEvent[];
  case_type: string;
  summary: string;
  metadata: SummaryMetadata;
}

interface ApiError {
  error: string;
  message: string;
  detail?: { error: string; message: string };
}

type AppState = "upload" | "processing" | "results" | "error";

// ------------------------------------------------------------------ //
// Constants
// ------------------------------------------------------------------ //

const MAX_FILE_SIZE = 20 * 1024 * 1024; // 20 MB

const PROCESSING_MESSAGES = [
  "Reading document...",
  "Extracting text...",
  "Analyzing case details...",
  "Generating summary...",
];

const CASE_TYPE_LABELS: Record<string, string> = {
  custody: "Custody",
  divorce: "Divorce",
  support: "Support",
  mixed: "Mixed",
  other: "Other",
};

const ROLE_LABELS: Record<string, string> = {
  petitioner: "Petitioner",
  respondent: "Respondent",
  appellant: "Appellant",
  defendant: "Defendant",
  plaintiff: "Plaintiff",
  judge: "Judge",
  witness: "Witness",
  lawyer: "Lawyer",
  child: "Child",
  other: "Other",
};

const DISCLAIMER =
  "This summary is AI-generated and may contain errors. All facts, dates, and amounts should be verified against the source document before use in legal proceedings.";

function formatCite(pages?: number[]): string {
  if (!pages || pages.length === 0) return "";
  return ` (p. ${pages.join(", ")})`;
}

function extractFact(fact: string | KeyFact): { text: string; pages: number[] } {
  if (typeof fact === "string") return { text: fact, pages: [] };
  return { text: fact.text, pages: fact.pages ?? [] };
}

// ------------------------------------------------------------------ //
// Markdown export
// ------------------------------------------------------------------ //

function buildMarkdown(data: CaseSummary): string {
  const lines: string[] = [];
  lines.push(`# Case Summary — ${data.metadata.filename}`);
  lines.push("");
  lines.push(`**Case type:** ${CASE_TYPE_LABELS[data.case_type] ?? data.case_type}`);
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  lines.push(data.summary);
  lines.push("");

  lines.push("## Parties");
  lines.push("");
  lines.push("| Name | Role | Aliases | Source |");
  lines.push("|------|------|---------|--------|");
  for (const p of data.parties) {
    const role = ROLE_LABELS[p.role] ?? p.role;
    const aliases = p.aliases.length > 0 ? p.aliases.join(", ") : "—";
    const src = p.source_pages?.length ? `p. ${p.source_pages.join(", ")}` : "";
    lines.push(`| ${p.name} | ${role} | ${aliases} | ${src} |`);
  }
  lines.push("");

  lines.push("## Key Facts");
  lines.push("");
  for (let i = 0; i < data.key_facts.length; i++) {
    const { text, pages } = extractFact(data.key_facts[i]);
    const cite = pages.length ? ` (p. ${pages.join(", ")})` : "";
    lines.push(`${i + 1}. ${text}${cite}`);
  }
  lines.push("");

  lines.push("## Timeline");
  lines.push("");
  lines.push("| Date | Event | Source |");
  lines.push("|------|-------|--------|");
  for (const t of data.timeline) {
    const src = t.pages?.length ? `p. ${t.pages.join(", ")}` : "";
    lines.push(`| ${t.date} | ${t.event} | ${src} |`);
  }
  lines.push("");

  // Verification checklist
  lines.push("## Verification Checklist");
  lines.push("");
  if (data.parties.length > 0) {
    const names = data.parties.map((p) => {
      const cite = p.source_pages?.length ? ` (p. ${p.source_pages.join(", ")})` : "";
      return `${p.name}${cite}`;
    });
    lines.push(`- [ ] Verify parties: ${names.join(", ")}`);
  }
  if (data.timeline.length > 0) {
    const dates = data.timeline.map((t) => {
      const cite = t.pages?.length ? ` (p. ${t.pages.join(", ")})` : "";
      return `${t.date}${cite}`;
    });
    lines.push(`- [ ] Verify dates: ${dates.join(", ")}`);
  }
  if (data.key_facts.length > 0) {
    lines.push(`- [ ] Verify ${data.key_facts.length} key facts against source pages`);
  }
  lines.push("");

  lines.push("---");
  lines.push(`*${DISCLAIMER}*`);
  lines.push("");
  lines.push(`*Generated by CaseLens | Model: ${data.metadata.model} | Chunks: ${data.metadata.chunks_processed}*`);
  lines.push("");

  return lines.join("\n");
}

function downloadMarkdown(data: CaseSummary) {
  const md = buildMarkdown(data);
  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  const base = data.metadata.filename.replace(/\.pdf$/i, "");
  a.download = `${base}_summary.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ------------------------------------------------------------------ //
// Main page component
// ------------------------------------------------------------------ //

export default function Home() {
  const [state, setState] = useState<AppState>("upload");
  const [summary, setSummary] = useState<CaseSummary | null>(null);
  const [errorMsg, setErrorMsg] = useState("");
  const [processingIdx, setProcessingIdx] = useState(0);
  const [dragOver, setDragOver] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Clean up interval on unmount
  useEffect(() => {
    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
  }, []);

  // Start fake progressive messages
  const startProcessingMessages = useCallback(() => {
    setProcessingIdx(0);
    let idx = 0;
    intervalRef.current = setInterval(() => {
      idx++;
      if (idx < PROCESSING_MESSAGES.length) {
        setProcessingIdx(idx);
      } else {
        // Stay on last message
        if (intervalRef.current) clearInterval(intervalRef.current);
      }
    }, 2500);
  }, []);

  // Upload file to backend
  const uploadFile = useCallback(
    async (file: File) => {
      // Frontend validation
      if (!file.name.toLowerCase().endsWith(".pdf")) {
        setErrorMsg("Please upload a PDF file.");
        setState("error");
        return;
      }
      if (file.size > MAX_FILE_SIZE) {
        setErrorMsg("File exceeds the 20 MB size limit.");
        setState("error");
        return;
      }

      setState("processing");
      startProcessingMessages();

      try {
        const formData = new FormData();
        formData.append("file", file);

        const res = await fetch("/api/summarize", {
          method: "POST",
          body: formData,
        });

        if (intervalRef.current) clearInterval(intervalRef.current);

        if (!res.ok) {
          const body: ApiError = await res.json().catch(() => ({
            error: "unknown",
            message: `Server returned ${res.status}`,
          }));
          const msg =
            body.detail?.message || body.message || `Server error (${res.status})`;
          setErrorMsg(msg);
          setState("error");
          return;
        }

        const data: CaseSummary = await res.json();
        setSummary(data);
        setState("results");
      } catch {
        if (intervalRef.current) clearInterval(intervalRef.current);
        setErrorMsg("Could not connect to the server. Is the backend running?");
        setState("error");
      }
    },
    [startProcessingMessages]
  );

  // Reset to upload state
  const reset = useCallback(() => {
    setState("upload");
    setSummary(null);
    setErrorMsg("");
    setProcessingIdx(0);
    if (intervalRef.current) clearInterval(intervalRef.current);
    if (fileInputRef.current) fileInputRef.current.value = "";
  }, []);

  // File selection handler
  const onFileSelect = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (file) uploadFile(file);
    },
    [uploadFile]
  );

  // Drag-and-drop handlers
  const onDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(true);
  }, []);

  const onDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
  }, []);

  const onDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setDragOver(false);
      const file = e.dataTransfer.files[0];
      if (file) uploadFile(file);
    },
    [uploadFile]
  );

  // ---------------------------------------------------------------- //
  // Upload State
  // ---------------------------------------------------------------- //
  if (state === "upload") {
    return (
      <div className="flex flex-col items-center gap-8 pt-8">
        <div className="text-center max-w-lg">
          <h2 className="text-3xl font-bold text-[var(--navy)] mb-3">
            Analyze Your Case File
          </h2>
          <p className="text-gray-500 text-lg">
            Upload a legal PDF to receive a structured summary with parties,
            key facts, timeline, and case analysis.
          </p>
        </div>

        <div
          onDragOver={onDragOver}
          onDragLeave={onDragLeave}
          onDrop={onDrop}
          onClick={() => fileInputRef.current?.click()}
          className={`
            w-full max-w-xl border-2 border-dashed rounded-xl p-16
            flex flex-col items-center gap-4 cursor-pointer
            transition-all duration-200
            ${dragOver
              ? "border-[var(--gold)] bg-[var(--gold-muted)] scale-[1.01]"
              : "border-gray-300 hover:border-[var(--gold)] hover:bg-gray-50"
            }
          `}
        >
          {/* Upload icon */}
          <svg
            className="w-14 h-14 text-gray-400"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={1.5}
              d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
            />
          </svg>
          <p className="text-lg text-[var(--navy)] font-medium">
            Drop your PDF here, or click to browse
          </p>
          <p className="text-sm text-gray-400">PDF files only, up to 20 MB</p>
        </div>

        <input
          ref={fileInputRef}
          type="file"
          accept=".pdf,application/pdf"
          onChange={onFileSelect}
          className="hidden"
        />
      </div>
    );
  }

  // ---------------------------------------------------------------- //
  // Processing State
  // ---------------------------------------------------------------- //
  if (state === "processing") {
    return (
      <div className="flex flex-col items-center gap-8 pt-24">
        {/* Spinner */}
        <div className="relative w-20 h-20">
          <div className="absolute inset-0 border-4 border-gray-200 rounded-full" />
          <div className="absolute inset-0 border-4 border-t-[var(--gold)] rounded-full animate-spin-slow" />
        </div>

        <div className="text-center">
          <p className="text-xl text-[var(--navy)] font-medium animate-pulse-slow">
            {PROCESSING_MESSAGES[processingIdx]}
          </p>
          <p className="text-sm text-gray-400 mt-3">
            This may take a moment for longer documents
          </p>
        </div>

        {/* Progress dots */}
        <div className="flex gap-2 mt-4">
          {PROCESSING_MESSAGES.map((_, i) => (
            <div
              key={i}
              className={`w-2.5 h-2.5 rounded-full transition-colors duration-500 ${i <= processingIdx
                ? "bg-[var(--gold)]"
                : "bg-gray-300"
                }`}
            />
          ))}
        </div>
      </div>
    );
  }

  // ---------------------------------------------------------------- //
  // Error State
  // ---------------------------------------------------------------- //
  if (state === "error") {
    return (
      <div className="flex flex-col items-center gap-6 pt-16">
        <div className="w-16 h-16 rounded-full bg-red-50 flex items-center justify-center">
          <svg
            className="w-8 h-8 text-red-500"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4.5c-.77-.833-2.694-.833-3.464 0L3.34 16.5c-.77.833.192 2.5 1.732 2.5z"
            />
          </svg>
        </div>
        <div className="text-center max-w-md">
          <h3 className="text-xl font-bold text-[var(--navy)] mb-2">
            Something went wrong
          </h3>
          <p className="text-gray-500">{errorMsg}</p>
        </div>
        <button
          onClick={reset}
          className="px-6 py-2.5 bg-[var(--navy)] text-white rounded-lg
                     hover:bg-[var(--navy-light)] transition-colors font-medium"
        >
          Try Again
        </button>
      </div>
    );
  }

  // ---------------------------------------------------------------- //
  // Results State
  // ---------------------------------------------------------------- //
  if (state === "results" && summary) {
    return (
      <div className="space-y-8 pb-12">
        {/* Header bar */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-2xl font-bold text-[var(--navy)]">
              Case Summary
            </h2>
            <p className="text-sm text-gray-400 mt-1">
              {summary.metadata.filename} &middot;{" "}
              {CASE_TYPE_LABELS[summary.case_type] ?? summary.case_type} case
              &middot; {summary.metadata.chunks_processed} chunk
              {summary.metadata.chunks_processed !== 1 ? "s" : ""} processed
            </p>
          </div>
          <div className="flex gap-3">
            <button
              onClick={() => downloadMarkdown(summary)}
              className="px-5 py-2.5 border border-[var(--gold)] text-[var(--gold)]
                         rounded-lg hover:bg-[var(--gold-muted)] transition-colors
                         font-medium text-sm flex items-center gap-2"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Export Markdown
            </button>
            <button
              onClick={reset}
              className="px-5 py-2.5 bg-[var(--navy)] text-white rounded-lg
                         hover:bg-[var(--navy-light)] transition-colors
                         font-medium text-sm"
            >
              New Analysis
            </button>
          </div>
        </div>

        {/* Narrative Summary */}
        <section className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
          <h3 className="text-lg font-bold text-[var(--navy)] mb-3 flex items-center gap-2">
            <span className="w-1 h-5 bg-[var(--gold)] rounded-full inline-block" />
            Summary
          </h3>
          <p className="text-gray-700 leading-relaxed whitespace-pre-line">
            {summary.summary}
          </p>
        </section>

        {/* Parties Table */}
        <section className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
          <h3 className="text-lg font-bold text-[var(--navy)] mb-3 flex items-center gap-2">
            <span className="w-1 h-5 bg-[var(--gold)] rounded-full inline-block" />
            Parties
          </h3>
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="py-2 pr-4 text-sm font-semibold text-gray-500 uppercase tracking-wider">
                    Name
                  </th>
                  <th className="py-2 pr-4 text-sm font-semibold text-gray-500 uppercase tracking-wider">
                    Role
                  </th>
                  <th className="py-2 pr-4 text-sm font-semibold text-gray-500 uppercase tracking-wider">
                    Aliases
                  </th>
                  <th className="py-2 text-sm font-semibold text-gray-500 uppercase tracking-wider">
                    Source
                  </th>
                </tr>
              </thead>
              <tbody>
                {summary.parties.map((p, i) => (
                  <tr key={i} className="border-b border-gray-50 last:border-0">
                    <td className="py-3 pr-4 font-medium text-[var(--navy)]">
                      {p.name}
                    </td>
                    <td className="py-3 pr-4 text-gray-600">
                      {ROLE_LABELS[p.role] ?? p.role}
                    </td>
                    <td className="py-3 pr-4 text-gray-500">
                      {p.aliases.length > 0 ? p.aliases.join(", ") : "—"}
                    </td>
                    <td className="py-3 text-gray-400 text-sm">
                      {p.source_pages?.length ? `p. ${p.source_pages.join(", ")}` : ""}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Key Facts */}
        <section className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
          <h3 className="text-lg font-bold text-[var(--navy)] mb-3 flex items-center gap-2">
            <span className="w-1 h-5 bg-[var(--gold)] rounded-full inline-block" />
            Key Facts
          </h3>
          <ol className="list-decimal list-inside space-y-2">
            {summary.key_facts.map((fact, i) => {
              const { text, pages } = extractFact(fact);
              return (
                <li key={i} className="text-gray-700 leading-relaxed pl-1">
                  {text}
                  {pages.length > 0 && (
                    <span className="text-gray-400 text-sm ml-1">
                      (p. {pages.join(", ")})
                    </span>
                  )}
                </li>
              );
            })}
          </ol>
        </section>

        {/* Timeline Table */}
        <section className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
          <h3 className="text-lg font-bold text-[var(--navy)] mb-3 flex items-center gap-2">
            <span className="w-1 h-5 bg-[var(--gold)] rounded-full inline-block" />
            Timeline
          </h3>
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="border-b border-gray-200">
                  <th className="py-2 pr-4 text-sm font-semibold text-gray-500 uppercase tracking-wider w-40">
                    Date
                  </th>
                  <th className="py-2 pr-4 text-sm font-semibold text-gray-500 uppercase tracking-wider">
                    Event
                  </th>
                  <th className="py-2 text-sm font-semibold text-gray-500 uppercase tracking-wider w-24">
                    Source
                  </th>
                </tr>
              </thead>
              <tbody>
                {summary.timeline.map((t, i) => (
                  <tr key={i} className="border-b border-gray-50 last:border-0">
                    <td className="py-3 pr-4 font-medium text-[var(--navy)] whitespace-nowrap">
                      {t.date}
                    </td>
                    <td className="py-3 pr-4 text-gray-600">{t.event}</td>
                    <td className="py-3 text-gray-400 text-sm">
                      {t.pages?.length ? `p. ${t.pages.join(", ")}` : ""}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Verification Checklist */}
        <section className="bg-amber-50 rounded-xl border border-amber-200 p-6">
          <h3 className="text-lg font-bold text-[var(--navy)] mb-3 flex items-center gap-2">
            <span className="w-1 h-5 bg-amber-400 rounded-full inline-block" />
            Verification Checklist
          </h3>
          <ul className="space-y-2">
            {summary.parties.length > 0 && (
              <li className="flex items-start gap-2 text-gray-700">
                <input type="checkbox" className="mt-1 accent-[var(--gold)]" />
                <span>
                  Verify parties:{" "}
                  {summary.parties.map((p) => `${p.name}${formatCite(p.source_pages)}`).join(", ")}
                </span>
              </li>
            )}
            {summary.timeline.length > 0 && (
              <li className="flex items-start gap-2 text-gray-700">
                <input type="checkbox" className="mt-1 accent-[var(--gold)]" />
                <span>
                  Verify dates:{" "}
                  {summary.timeline.map((t) => `${t.date}${formatCite(t.pages)}`).join(", ")}
                </span>
              </li>
            )}
            {summary.key_facts.length > 0 && (
              <li className="flex items-start gap-2 text-gray-700">
                <input type="checkbox" className="mt-1 accent-[var(--gold)]" />
                <span>Verify {summary.key_facts.length} key facts against source pages</span>
              </li>
            )}
          </ul>
        </section>

        {/* Disclaimer */}
        <p className="text-center text-xs text-gray-400 italic px-8">
          {DISCLAIMER}
        </p>

        {/* Metadata footer */}
        <p className="text-center text-xs text-gray-400">
          Analyzed with {summary.metadata.model} &middot;{" "}
          {summary.metadata.chunks_processed} chunk
          {summary.metadata.chunks_processed !== 1 ? "s" : ""} processed
        </p>
      </div>
    );
  }

  return null;
}
